### ISSUE TITLE
Convert CSS to SASS

### ISSUE THREAD

**Issue by caryfitzhugh** [mx3/mx#1]
Convert the (maybe there aren't any?) CSS on the site - or at least any new styles, can be written in SCSS.

**Comment by mjy** [comment]
Hey- the million dollar question- can you convert/roundtrip SASS back to CSS (in some automated way)?  If so let's start using SASS.

**Comment by caryfitzhugh** [comment]
SASS <-> CSS is an easy conversion in general.

I can look into adding SASS, we can put an scss file somewhere for us to add
SASS to.

**Comment by mjy** [comment]
Let's go for it.  The CSS needs a major overhaul at some point- can start simplifying things in that file.  I want to focus on using HTML 5 elements as well where possible, more on that in a bit.

**Comment by caryfitzhugh** [comment]
ok. I'll do this one tonight.

**Comment by caryfitzhugh** [comment]
I'm going to include Jammit in this - since it makes things much cleaner when it comes to assets...  I think you'll like it. :)
And SASS just drops into it.

**Comment by mjy** [comment]
Sounds good.

**Comment by caryfitzhugh** [comment]
Added bourbon mixins. they are awesome. ;) 

One can just make submit buttons look really nice:  http://i.imgur.com/yZZP9.png

If you want this look - just add this to the app/sass/base.scss file:

```
input[type='submit'] {
    @include button;
}
```

You can customize it a lot - look at this link and search for "Buttons". I did a screen show below: 
https://github.com/thoughtbot/bourbon 
http://i.imgur.com/Nw5yk.png

**Comment by caryfitzhugh** [comment]
The bourbon mixins let us do things much DRY'er like:

instead of having to do:

```
-moz-border-radius  ...
-webkit-border-radius ...
border-radius ....
```

We can just do:

```
@include border-radius( .... ) 
```

**Comment by mjy** [comment]
Are those styles completely css?  Very anti any image-based elements
(in fact, they're not allowed in mx).

On Wed, Sep 28, 2011 at 9:56 PM, caryfitzhugh
reply@reply.github.com
wrote:

**Comment by caryfitzhugh** [comment]
Totally image-less... total awesomness! 
You can do _so_ much cool stuff with plain ol CSS3...

**Comment by caryfitzhugh** [comment]
These are a bit much - but all CSS:
http://girliemac.com/sandbox/button.html

These are more subdued: 
http://webdesignerwall.com/tutorials/css3-gradient-buttons

And the stuff that bourbon has out of the box are pretty nice as well....

**Comment by caryfitzhugh** [comment]
I too hate HATE images.. bleck.  Such a total pain.

**Comment by caryfitzhugh** [comment]
ok - it looks good to me.  Jammit / SASS / Bourbon mixins.  

I moved all the new styles I've written for MX and put them into the app/sass/base.scss file.

Included a few bourbon mixins as well to DRY and clean it up even more.

**Comment by mjy** [comment]
Sounds good- if you can drop a couple comments/pointers in the
pertinent places that would be great.

On Wed, Sep 28, 2011 at 10:19 PM, caryfitzhugh
reply@reply.github.com
wrote:

**Comment by caryfitzhugh** [comment]
I'll put some comments in the following files:

app/sass/base.scss
config/assets.yml

Those are the two places to look...

Comments pushing soon....
