### ISSUE TITLE
Style Block Helpers

### ISSUE THREAD

**Issue by caryfitzhugh** [mx3/mx#10]
DEPRECATION WARNING: <% %> style block helpers are deprecated. Please use <%= %>. (called from _app_views_otu__ajax_list_html_erb___2133994688901804413_2188762660_4293751461394165690 at /Users/cfitzhugh/working/mx3/app/views/otu/_ajax_list.html.erb:16)

**Comment by mjy** [comment]
Fixed in 5d8f826c30c29422a8f5f2279b25d5d8549938de
