### ISSUE TITLE
Update figures popup to jQuery

### ISSUE THREAD

**Issue by mjy** [mx3/mx#11]
This is perhaps the most complex update required.  The figure functionality is very similar to the tag functionality:
- Modal popup, polymorphic relationship to any object with an ID, just like Tags
- Form has two major components: 1) A receiving cart (in the new version simplify just to some div, 2) A simple AJAX driven search
- "Cart" is populated with existing images attached to the object being figured
- Figures in the cart can be individually edited themselves in two ways- 1) Their caption can be edited (edit in place field hopefully) and 2) their order can be re-arranged.
- Existing search results can be selected by either 1) dragging them into the cart; or 2) clicking a select link 
- !!Ignore the drag/drop functionality in the updated code, it's overkill that doesn't get used (we added 2) after the fact).

Steps to get going:
- You'll have to add a new image (hack fixed this locally, so it's at least possible).  Images need a file, and one of OTU or Specimen (for testing use former)
- Create a new Character (just need name)
- Create a new state for that character (need state and name)
- Click Fig next to the first state's "figure"

Other
- The image model is just metadata about the image itself. 
- An image can have many ImageDescriptions which describe the content of the image
- The images tab renders all the ImageDescriptions records, not Image records, so you might see some images duplicated in the ajax list
- All images can be overlayed with svg using svgweb- i.e. try and use the same display code/tags/helpers if at all possible

Click "fig" on say, projects/12/chr/show/1399 for example in production for the existing functionality.

**Comment by caryfitzhugh** [comment]
Tired and don't have much energy tonight -- this looks like a whopper - so I'll try to hit it tmw or friday when I have a good block of time to get started...

I looked on the production page, clicked on fig and didn't really get what images could be dragged or what not.

Could you hook me up with a few screenshots showing what you're talking about?

**Comment by mjy** [comment]
A couple of screenshots and notes: http://imgur.com/a/mb48R

I made it sound a little more complicated than I think it is.  Completely ignore the drag-drop functionality in the old version, it's not being replicated here.  There are 4 major components in the new one (1-4 in screenshots).

1 - A results div - a partial listing the Figures presently attached to the Object being figured
2 - A search div - holds a form and a result div
3 - A search form div
4 - A image search result div

User clicks on "Fig".  Gets modal.  Sees either 1) existing figures or 2) a black div.  User adds some criteria to search box, then searches, find some or no ImageDescriptions.  Click on an ImageDescription to add it to 1) as a figure record.  Once a figure record is created some additional functionality is possible (see arrowed annotations).

If I get time this aft. I might try and mock some things using your existing Tag code as a reference.  Need to see if I can grok it.

**Comment by caryfitzhugh** [comment]
ok, back in the saddle... taking a stab at this one now.
Sorry it's been a while - lots going on in life.

**Comment by caryfitzhugh** [comment]
Drat.  Didn't get very far.
The DB rename, and then found some missing px's on the color picker css files.

But now - there are 2 issues.
#12 - I get a "no marshal_dump is defined for class Mutex" exception when I go to ontology or many other tabs.  Not sure what to do, since it's not an exception in our stack, looks like something in rails...  no clue.  Maybe you have an idea.

#14 - I have no idea how to set up the system to add / remove these figures? Can you get me up with some skeleton data - like -- what is a simple thing I can create that can be tagged with figures -- and what is a simple way to add some figures to the system.

Once I get that, I think I'll fire up the modal to do searching and then we'll go from there...

Thanks,
Cary

**Comment by mjy** [comment]
Realized I didn't give you instructions for dataset- thought I'd done that.

Do this (after pulling):
- create a new character off the characters tab, just give it a name, nothing else is needed
- add an image - you'll just have to attach it to an OTU, nothing else is needed, you will have to setup ImageMagik if you don't have it, and configure your /public folders as describe in the installation help in the wiki
- click on the figure_tag link I put on the top of the layout.

**Comment by mjy** [comment]
Just fixing the partial rendering for the figure_tag now... realized it's not html_safe.

**Comment by mjy** [comment]
Stubbing out this code based on the figure- push coming.

**Comment by mjy** [comment]
Sorry about the DB rename- that came from Katja, didn't tell her about how to properly fix.  Can you revert and push?

**Comment by mjy** [comment]
Cary- I've pushed some more stubbing of figure functionality- back in your hands.  After you create a new character the fig link should work.  Added some comments inline as to where things need to happen.

**Comment by mjy** [comment]
Taking that back- I'm still hacking on it- I'll push frequently but just make sure to check in here before you get into it again.

**Comment by mjy** [comment]
Going to close this issue and break out specifics now that the basic functionality is done.
