### ISSUE TITLE
no marshal_dump is defined for class Mutex

### ISSUE THREAD

**Issue by mjy** [mx3/mx#12]
This is perhaps a problem with the named_scopes that uses regexes or some character encoding.  Looking into fixing this now.

**Comment by caryfitzhugh** [comment]
I feel like this has come up recently... I'll try git-bisect...

**Comment by caryfitzhugh** [comment]
Phooey.. nope.  It's been broke at least since I had started to help.
Can you reproduce it?

**Comment by mjy** [comment]
Yes, I can.  It is related to either 1) named scopes, or 2) character
encoding. I tracked down the problem originally by commenting out
various lines in the controllers.

On Sun, Sep 25, 2011 at 10:58 PM, caryfitzhugh
reply@reply.github.com
wrote:

**Comment by mjy** [comment]
Are there places other than content/list that throw this error?  Might be able to close it now.

**Comment by caryfitzhugh** [comment]
I haven't seen this in a long time -- I'll just close it.
