### ISSUE TITLE
display flash[:notice] as for successfull Tags

### ISSUE THREAD

**Issue by mjy** [mx3/mx#13]
Would be nice to use the same hook that successful Tag notice is displayed for all flash[:notice] messages.

**Comment by caryfitzhugh** [comment]
It can be -- or should be... I can look into it... it should be displaying
all flash in the same part... I might have missed it though.

**Comment by mjy** [comment]
I noticed the `notice "foo"` approach- I'm guessing we just change
`flash[:notice] = "foo"` to use the former?

On Fri, Sep 23, 2011 at 8:14 PM, caryfitzhugh
reply@reply.github.com
wrote:

> It can be -- or should be... I can look into it... it should be displaying
> all flash in the same part... I might have missed it though.
> 
> On Thu, Sep 22, 2011 at 11:20 AM, Matt <

**Comment by caryfitzhugh** [comment]
Yeah -- that's the only changes there.  
I'll look into the layout for why it's not displaying...

**Comment by caryfitzhugh** [comment]
Ok ! Pushed.
