### ISSUE TITLE
Styling On Figures Modal

### ISSUE THREAD

**Issue by caryfitzhugh** [mx3/mx#17]
Look into styling the figures modal --

vertical scrolling
on the image search result- that result can be very large in some
cases, and the modal currently locks things to a single screen.

**Comment by mjy** [comment]
When a search for images completes the modal closes after the spinner completes.

**Comment by caryfitzhugh** [comment]
I couldn't get the modal to come up..  weird.

I found another task and thought it said to create an image.

new image page comes up with this: http://i.imgur.com/3zaWW.png

Looks like it's missing an image_description/_picker file... or something.

If you could shoot me the steps again to bring up the figures modal, I can try to fix the spinner problem and give it some styling love...

**Comment by mjy** [comment]
Create a new character, then add a state.  You should see a "Fig" link for the state.

The modal breaking could be an issue with the new routes file (see the other issue I've assigned to you).  I have one other lead there, will try it out tonite after I commit some edge code to 2.3.10.

**Comment by mjy** [comment]
Tweak to the image form posted, solves your problem re the png.

I forgot about adding images for you though- easiest is to Images->'more option' ->Morphbank options-> new.  Use one of these ids: 782649,781432,781526,781530,781557,781609,782651,781450,781491,781534,781559,781613,782653,781475.  You'll have to have OTUs created.

**Comment by caryfitzhugh** [comment]
Phooey... Stuck installing imagemagick -- i noticed the system looking for
/usr/local/bin/identify

Tried brew install imagemagick.

but -- for some reason that recipe is looking for
github.com/adamv/ImageMagick -- which does not exist.

phooey.

Ended up installing from source -- and finally got my images visible in the
figures modal.

I am pooped now though, but prepped for some progress tomorrow!

Thanks,
Cary

**Comment by mjy** [comment]
Make sure to check out the install instructions on the wiki re the
folders/paths required for storing images if you haven't already.
Installing imagemagick from source is always easier ;).

On Sat, Oct 29, 2011 at 11:04 PM, caryfitzhugh
reply@reply.github.com
wrote:

> Phooey... Stuck installing imagemagick -- i noticed the system looking for
> /usr/local/bin/identify
> 
> Tried brew install imagemagick.
> 
> but -- for some reason that recipe is looking for
> github.com/adamv/ImageMagick -- which does not exist.
> 
> phooey.
> 
> Ended up installing from source -- and finally got my images visible in the
> figures modal.
> 
> I am pooped now though, but prepped for some progress tomorrow!
> 
> Thanks,
> Cary
> 
> On Wed, Oct 26, 2011 at 10:48 PM, Matt <

**Comment by caryfitzhugh** [comment]
Started to look at styling it, then noticed that there were 4 JS errors on
the page, because inplace editing was not jquery-ified.

So - took about 2 hours and wrote an inplace editor plugin, and added it to
all of the inplace edit fields on the CHR show page.

Should we make a 'grind' task to verify that all of the inplace editors on
the site are converted?

Think I can get to styling tomorrow...  Thanks.

**Comment by mjy** [comment]
Good call on going ahead updating the in-places, and yes, let's make a
grind task to polish off the remainders.

M

On Tue, Nov 1, 2011 at 12:16 AM, caryfitzhugh
reply@reply.github.com
wrote:

> Started to look at styling it, then noticed that there were 4 JS errors on
> the page, because inplace editing was not jquery-ified.
> 
> So - took about 2 hours and wrote an inplace editor plugin, and added it to
> all of the inplace edit fields on the CHR show page.
> 
> Should we make a 'grind' task to verify that all of the inplace editors on
> the site are converted?
> 
> Think I can get to styling tomorrow...  Thanks.
> 
> On Sun, Oct 30, 2011 at 10:43 AM, Matt <
