### ISSUE TITLE
General purpose tooltip popups

### ISSUE THREAD

**Issue by mjy** [mx3/mx#18]
Need a simple mechanism for generating tooltips. Both inline or AJAX populated would be nice.  Would be great if we could do something like `content_tag :div, "some content",  'data-inline-tool-tip' => "some inline content'` or maybe `'data-ajax-tooltip' => 'partial/to/load')`.  Bonus points for altering those elements with popup data automatically with some visual cue (perhaps a different background color, or subtle border).

**Comment by caryfitzhugh** [comment]
I think to handle the visual cue - we could just have it add a CSS class --
and then we'll style it however we want...

**Comment by mjy** [comment]
Sounds good- I just don't want to have to manually include a styling.

On Mon, Sep 26, 2011 at 11:31 AM, caryfitzhugh
reply@reply.github.com
wrote:

> I think to handle the visual cue - we could just have it add a CSS class --
> and then we'll style it however we want...
> 
> On Mon, Sep 26, 2011 at 11:29 AM, Matt <

**Comment by caryfitzhugh** [comment]
Starting on this tonight....

**Comment by caryfitzhugh** [comment]
Loading ajax: http://i.imgur.com/HQH6U.png
Just content: http://i.imgur.com/3aX5F.png
Loaded through AJAX: http://i.imgur.com/14JB1.png

Once again, the size of the tooltip is defined by the tooltip content.  Just
like the modals.

It's got a small notch -- CSS trick, pretty nifty.

I hope this is what you needed.

Here are the two ways to interact with it:

set data-tooltip using the tooltip_render helper (CGI.escapeHTML and
render_to_string)
like so:

<a href="" data-tooltip="<%=
tooltip_render(:partial=>"shared/test_tooltip")%>"> LINK FOR INLINE </a>

If you want it to load by AJAX -- you can do this:

<a href=""
data-tooltip="/projects/1/tag/new?html_selector=%23tags_html_otu_1&tag_obj_class=Otu&tag_obj_id=1">
LINK FOR AJAX </a>

It remembers if it loaded the stuff through AJAX too -- so it can pop it up
quickly once it has already been loaded.

Seems pretty cool - wasn't too much work to build either.

The way the JS code knows to do AJAX or not is pretty simple.. just looks
for a "/" at the beginning of the content.  Which I believe is good enough
for all of the forseeable cases.

Hope it meets all the needs you have.

Thanks
Cary

**Comment by mjy** [comment]
Looks great, I like the simplicity.  Haven't tried it- but is it possible to have popups for non <a> elements?

**Comment by caryfitzhugh** [comment]
Yes. Easy, just put the data- ttr
On Sep 28, 2011 10:14 AM, "Matt" <
reply@reply.github.com>
wrote:
