### ISSUE TITLE
Update sortable/draggable lists to use jQuery and/or HTML5

### ISSUE THREAD

**Issue by mjy** [mx3/mx#19]
We use drag/drop lists in a bunch of different places.  If you can get it working for Otus/Otu_groups I can like extend the pattern to the other places (chrs/chr_groups, chrs/projs, authors/refs).

Hopefull this is pretty straightforward.  Show a populated otu_group for in production for an example, e.g. projects/12/otu_group/show/383.  The [drag] text is the anchor.  

Might want to check out HTML5 capabilities- http://html5doctor.com/native-drag-and-drop/

Native would be even better option than jQuery I think.

**Comment by caryfitzhugh** [comment]
Working.  Going to do jQuery - our mx-sortable plugin.  If we need to flip over to HTML5 at some point, we can do so.

**Comment by caryfitzhugh** [comment]
Does this work?
http://i.imgur.com/q1mYI.png

Am I supposed to add the OtuGroups through that interface?

I tried -- I even had to fix a bug (I think) -- but now the autocompleter returns my OtuGroup - and I _think_ it's supposed to be adding it. but it doesn't seem to.  Thoughts? I believe that I'm close to implementing the sortable - but can't test.

I figured that if I added 3 otu groups to my otu_group, then I should have been able to drag n drop (and ajax delete -- I added that...) the otu_group.

**Comment by caryfitzhugh** [comment]
I've also been adding my little drag_handle to the sortables.  It's just a couple divs, we can pull it out if you don't like it.

Check out what I just pushed, it's 1/2 working... but... 

Thanks,
Cary

**Comment by mjy** [comment]
An Otu_group contains multiple OTUs.  The auto picker should be OTUs
(I think).  Looking now...

On Mon, Oct 3, 2011 at 10:34 PM, caryfitzhugh
reply@reply.github.com
wrote:

**Comment by mjy** [comment]
Oh- I see- the add/subtract an OTU group means the _contents_ (OTUs) of that group- i.e. a bunch of OTUs -> set theory like.  I didn't actually get to testing if it works (it does in production).

**Comment by mjy** [comment]
"Add a single OTU definitely works now."

**Comment by caryfitzhugh** [comment]
Ok. Great. Will debug and finish the ortable tnight.
On Oct 4, 2011 10:55 AM, "Matt" <
reply@reply.github.com>
wrote:

**Comment by caryfitzhugh** [comment]
Added the code.
Converted to a table, since I think it looks a lot nicer and lined up that way.

added my first test for sort_otus! :)

updated minitest, so we get more than just 'Execpted the block to return true'

And that's all.

I think you said there was one other sortable you wanted updated -- if you want to point me at that one, I can do it, or I'll just work on the other assigned tasks.

Thanks.
Cary

**Comment by mjy** [comment]
Did you miss committing a file by any chance?  I'm seeing the tablified data but it's not being ajaxified.  Still trying to figure out if I'm overlooking something though.

**Comment by caryfitzhugh** [comment]
Uhoh... will check. 1 sec.
On Oct 6, 2011 11:03 AM, "Matt" <
reply@reply.github.com>
wrote:

**Comment by mjy** [comment]
No real rush- I just pushed my cumulative changes (all towards
cleaning up functional tests), so maybe there is a conflict on my
side.

On Thu, Oct 6, 2011 at 11:17 AM, caryfitzhugh
reply@reply.github.com
wrote:

**Comment by caryfitzhugh** [comment]
I tried it in FFX and it worked.

It is limited to the drag-handle right now.  I thought that was an
improvement -- just made it more clear where to drag from.  Maybe you are
expecting to drag the text as well? I can extend it to let you drag from
anywhere... let me know.

Thanks,
Cary
