### ISSUE TITLE
Make tags editable in modal

### ISSUE THREAD

**Issue by mjy** [mx3/mx#21]
Right now the link in tag/ts is link_to('edit', :action => :edit, :controller => :tag, :id => ts.id), which goes to the vanilla form. Let's use the modal popup to edit the tag.

Will have to provide a source_to_update_id (id of some div) and partial_to_render parameter to the modal so that we can redraw the div with with the contents of the edited tag.

Steps to test- create an OTU.  Tag it.  Show it, then click "tags" on the left (not "Tag").  Click the 'edit' link.

**Comment by caryfitzhugh** [comment]
Finished on this one.  
Had to update the modal to hide if there was no content in the response. 

Pushed to github.
