### ISSUE TITLE
Clean Out Test Suite And Start Over

### ISSUE THREAD

**Issue by caryfitzhugh** [mx3/mx#23]
We might want to just erase all the tests that are failing in there -- and start over.  

Then - we might want to just go through each tab of the site -- redefine what exactly each feature is going to need to do - 
and work through it.  That's the only way I know of to get a clean test suite going again....

Once we get that testing coverage, we can also be streamlining the install process so others can really start to use this tool (I think you mentioned this issue before).

Thinking about this more -- I think that I may be speaking too quickly -- you may be able to fix all the unit tests quickly and easily.

Then - functional tests are probably a bit more screwed up with the changes in Rails 3 and our tagging changes.

Anyway -- it would be helpful at some point to have us running rake test every time we do changes and making sure we don't break anything. :)

**Comment by mjy** [comment]
You're right on re getting tests cleaned up and starting to religiously run them, but I'm pretty sure ditching them and starting over isn't the way to go- definitely not for the unit tests, but I could see redoing all the functionals.  It won't take me long to get the rest to pass, and where they fail we need major refactoring.

**Comment by caryfitzhugh** [comment]
Cool -- I overstated it a bit.. sorry.. but the gist is to get them up n
going again.. cool.

Thanks

**Comment by mjy** [comment]
Going to close this until it can be evolved into a more specific suggestion (and tests work now).
