### ISSUE TITLE
Update to highest non Rails 3.1?

### ISSUE THREAD

**Issue by mjy** [mx3/mx#24]
Is there some reason (I vaguely remember something) for not updating past 3.0.7.  Don't want to go to 3.1 until we test clean etc., but we could go futher?!

**Comment by mjy** [comment]
Cary- let's update to 3.0.11 (AFAIKT that's that's the latest, if it's not, go with whatever 3.0.x branch is).  Should be trivial, but I'm assigning to you just in case something goes south.

**Comment by caryfitzhugh** [comment]
On it sir!

**Comment by caryfitzhugh** [comment]
done. n pushed. changelog doesn't seem like much changed but some bugfixes.
