### ISSUE TITLE
General purpose link_to JS to open in a new window 

### ISSUE THREAD

**Issue by mjy** [mx3/mx#25]
Need to emulate :target => '_blank' or the old :popup => true. I.e. result of click is opened in a new browser window.

**Comment by caryfitzhugh** [comment]
What is the usecase? As in - what will this do that just putting target
blank won't?
Thanks,
Cary
On Oct 3, 2011 2:50 PM, "Matt" <
reply@reply.github.com>
wrote:

**Comment by mjy** [comment]
Umm- for some reason I had it in my head that :target => '_blank' is
deprecated, of course it is HTML, so it's not.  Just close this, with
prejudice.  No more posting for me Mondays.

On Mon, Oct 3, 2011 at 3:14 PM, caryfitzhugh
reply@reply.github.com
wrote:
