### ISSUE TITLE
Fix functional tests failing with "Observable" based errors

### ISSUE THREAD

**Issue by mjy** [mx3/mx#26]
Think that was prototype code- basically observing select boxes and firing requests when they update.

**Comment by caryfitzhugh** [comment]
Ok - I found these.

I'm starting with the partial: app/views/chr/_code_with_form.html.erb

Replacing the observe_field helper, with a few data-\* attribute based plugins..  I think it should be pretty good.
However -- How can I see this page in 'real life'? Any ideas? Can't iron out the bugs until I can get the page up and play with it.

If you can't get back to me, I can probably figure most of them out - but if you have any quick thoughts on how to access certain parts of the site.....

These are the other partials.  if you can tell me how to 'activate' them / view them, that would be quite helpful. ;)

app/views/multikey/_cmp_otu.html.erb
app/views/otu/show/_content.html.erb
app/views/otu_group/show/_content_grid.html.erb
app/views/otu_group/show/_descriptions.erb
app/views/phenotype/_edit_count_phenotype.html.erb
app/views/phenotype/_edit_presence_absence_phenotype.html.erb
app/views/phenotype/_edit_relative_phenotype.html.erb
app/views/public/multikey/_cmp_otu.html.erb
app/views/public/multikey_simple/_cmp_otu.html.erb

**Comment by mjy** [comment]
Focus on these 3, ignore the others:

app/views/otu/show/_content.html.erb
app/views/otu_group/show/_content_grid.html.erb
app/views/otu_group/show/_descriptions.erb

The /show patter renders a partial in that views/show subfolder.  To
see it, first show a record for an otu or otu_group, then click a
navigationlink on the left that corresponds.

M

On Sat, Oct 8, 2011 at 11:23 PM, caryfitzhugh
reply@reply.github.com
wrote:

**Comment by caryfitzhugh** [comment]
I don't know how to 'create a content template and content types' ? For the first one.

Looking at the second ones.

**Comment by mjy** [comment]
Templates and content types are made on the content tab.

projects/1/content_template
projects/1/content_types

Make a content type first, then a content template.  Show a content
template to pick content types for that template.

On Sun, Oct 9, 2011 at 2:17 PM, caryfitzhugh
reply@reply.github.com
wrote:

**Comment by caryfitzhugh** [comment]
Think I've got the second two working...  cleaning up. will look at the other one (otu/show/_content) later / tmw.

**Comment by caryfitzhugh** [comment]
I got the Mutex error when clicking the content tab... ?

**Comment by mjy** [comment]
I've isolated the problem to the scope, but then I've hit a wall. If I don't use it but rather find Otus another way everything renders OK.  The problem seems to hold for other scopes as well.

 scope :with_content, where('otus.id IN (SELECT otu_id FROM contents)').includes(:taxon_name)

**Comment by caryfitzhugh** [comment]
interesting... I can poke about at it.

**Comment by caryfitzhugh** [comment]
I'll leave it alone actually - since I don't understand -- maybe you ahven't
pushed that code - but I see an old-school :conditions=>[] block in there.
 will check out a different task.

**Comment by caryfitzhugh** [comment]
Wondering -- I'll bet with_context is a rails internal method name (sounds
kindof rails-y)

Wonder if just changing the name fixes everything?

**Comment by mjy** [comment]
I managed to fix the scope using the non-sugary version.  Spent a lot of time trying to figure out exactly what was going on, with little success. Regardless, the with_content scope is fixed for Otu.rb, for now.

**Comment by caryfitzhugh** [comment]
Fantastic. :) sounds great.  I've been sick and on vaca this weekend, but
should b back in the saddle this week...

Thanks,
Cary
On Oct 23, 2011 5:43 PM, "Matt" <
reply@reply.github.com>
wrote:

**Comment by mjy** [comment]
Hey Cary,

I've been completely out of the loop for two weeks
(conferences/workshops) as well. Should have something new for you by
Tuesday I hope.  Might be time to hit the routes and get that squared
away.

M

On Sun, Oct 23, 2011 at 9:37 PM, caryfitzhugh
reply@reply.github.com
wrote:

**Comment by caryfitzhugh** [comment]
I think this was closed. ?
