### ISSUE TITLE
Update Confidence Popup to use new Tag pattern

### ISSUE THREAD

**Issue by mjy** [mx3/mx#29]
The confidence popup is more or less identical to the Tag functionality.  Steps to testing/updating coming shortly.

**Comment by mjy** [comment]
This is a popup that is applicable to any model that has a confidence_id field (see confidence.rb for configuration).  

Create new confidences (see production e.g.) projects/12/confidence. 

See the popup in action: projects/12/seq, click on an id in the pcr column. 

New for mx3: show only those confidences for named identically to the applicable model field (this isn't working in mx2, which detects the confidence list to show from the name of the confidence itself, see the `by_model` scope. 

Include a none option which set the option to none.

Should use identical modal popup to tags. 

Deploy with a confidence_tag(@ojbect) type helper.

**Comment by caryfitzhugh** [comment]
starting work. :)

**Comment by caryfitzhugh** [comment]
This is cool.  
I'm putting it on the confidences stuff -- and if I can remember, I'll try to apply it across the site to any element which has user-selected bg colors.

http://charliepark.tumblr.com/post/827693445/calculating-color-contrast-for-legible-text-in-ruby

Now you'll get black / white depending on the bg color - so you can always read the text :)

**Comment by mjy** [comment]
Looks just like a pluralization problem, all the controller/view paths
are now plural (so confidences, seqs rather than confidence, seq).

On Tue, Dec 27, 2011 at 9:46 AM, Cary FitzHugh
reply@reply.github.com
wrote:

**Comment by caryfitzhugh** [comment]
Ok - got the confidence controller mostly straight.  Sorting, creating, editing, colorizing, html_safeing.
Almost done with some light functional tests.

Then - going to go knock out the popup.

**Comment by caryfitzhugh** [comment]
Completed! Pushed.
