### ISSUE TITLE
Routing Deprecation Warning

### ISSUE THREAD

**Issue by caryfitzhugh** [mx3/mx#3]
DEPRECATION WARNING: You are using the old router DSL which will be removed in Rails 3.1. Please check how to update your routes file at: http://www.engineyard.com/blog/2010/the-lowdown-on-routes-in-rails-3/. (called from <top (required)> at /Users/cfitzhugh/working/mx3/config/routes.rb:1)

**Comment by mjy** [comment]
Hey Cary.  I struggled with getting the routes back and running.  I've created new unit tests to be run. Can you take a stab at getting things working.  The main issue is that controllers needs to map to things like

  /projects/1/otu/show/1

AND

 /projects/1/public/otu/show/1

Where the controller in the latter case is 'public/otu'.  It "just worked" in edge/2.3.10, but I couldn't get the conversion to run, and I think that the 2.3.10 code was probably too verbose.

**Comment by caryfitzhugh** [comment]
Close.  I have it working sometimes, then not the others... I'll check it out again tmw but I think i'm pretty durn close on it... :)

**Comment by mjy** [comment]
Sweet- I'm looking now too- just failing
test_recognizes_basic_public_pattern.  Sigh.  Is your strategy to use
a constraint on the match?

On Wed, Oct 26, 2011 at 11:21 PM, caryfitzhugh
reply@reply.github.com
wrote:

**Comment by caryfitzhugh** [comment]
I added a constraint on the match, and moved the public ones ahead of the
others so they would match first.  Still had some issues, but that was the
general direction.

**Comment by caryfitzhugh** [comment]
I just pushed my latest... And it works except for 2 routes.

And I don't know what the deal is, because if I go to the console and run
the commands to get the RouteSet, and run recognize_path through that --
all seems correct.

I wonder if you shouldn't just rearrange the routes...  Maybe put /public
as a suffix or prefix to the entire path?

you could have public_projects/ or something along those lines... not
really sure.

I think I'll stop fiddling with this now - and let you think on how you
wanted to proceed.

A suggestion would be that the routes are really quite complicated now and
just re-writing them may be the answer.
 It may be as simple as going to something more like scoped routes, and
treating things like resources (which is kindof what you did already).

Or just explicitly calling out the 10 controllers or so that you have.
 That's probably just as acceptable (I think?)

Anyway.. that's all for me.

Thanks,
Cary

**Comment by mjy** [comment]
Thanks for the assessment, same conclusion as I've hit.  I posted a gist and hit IRC about the issue and the consensus was to use scoped resources, so I'm going to take a stab at that- even though I think it might make for a huge routes file.

**Comment by caryfitzhugh** [comment]
You can do logic in there, so you culd do somethng like this:

[:otu, :otu_group, ..].each do |controller|
   ....  do your stuff here, the same for each controller...
End

That shouldn't be too large a routes file. Though, with a complx system, I
think routes can get large. Ours is pretty big on ziplist.

Anyway..
Cary
On Oct 29, 2011 12:36 PM, "Matt" <
reply@reply.github.com>
wrote:

**Comment by mjy** [comment]
Got ya.  I'm thinking about tearing down the controllers, renaming them all where necessary (pluralizing them) and using resources.  My only issue is we have lots of non-restful actions, and I _really_ don't want to have to declare them all in the routes.rb file.  Think that it's possible to use resources and then map other actions to :action?  I've been staring at docs for a while and it hasn't jumped out at me, but I haven't given up hope.

**Comment by caryfitzhugh** [comment]
I believe it should not be too bad to route things through a default route.

I haven't found it to be too bad to define things in your routes file.  I
consider it to kindof be the mapping between URLs to controllers - and
because of that defining it explicitly hasn't been too much of an issue
philosophically for me.

We actually tend to avoid using the default route for ziplist.  We have a
different situation, where we are live and need to debug stuff quickly. and
we we have random users doing random things I'd guess.  But it's nice (in
my mind) to have explict access points to my system - and I can trace /
track everything easily.  <shrug> It's more typing though....
Anyway.
Cary
On Oct 29, 2011 6:10 PM, "Matt" <
reply@reply.github.com>
wrote:

**Comment by mjy** [comment]
Done.  routes.rb is big, and somewhat nasty, but all resourceful now.

**Comment by caryfitzhugh** [comment]
Woooo hooo! Souns good. :)
On Dec 8, 2011 11:54 AM, "Matt" <
reply@reply.github.com>
wrote:

**Comment by caryfitzhugh** [comment]
OK! I got pretty far.  Fixed the one issue, then cleaned up a few things I
ran into, and got all the unit tests passing, and all but 2 functionals
passing.

The ones that don't pass are something with the routing of fast_code stuff.
I get errors one way, then reorder the declaration of the things in the
routes file -- and the errors change. Which means (to me) that the correct
routes are not being recognized ... bah.

I think the issue is that we are using assert_routing, which tries to
generate and route the path.  Might need to just change those routes or
something... so they aren't so similar.

We'll see...

thanks,
Cary

**Comment by caryfitzhugh** [comment]
Actually, might just need to make the two routes more different - so they
don't try to recognize each other....  we'll see...

**Comment by mjy** [comment]
Hey Cary,

Right.  I'm not too worried about it, we can just use a parameter
based route for them too.  I was actually working on getting that
one-click coding (that uses those routes) working yesterday with my
first js observer hack (I'm going to like these new js query
patterns).  I have one outstanding commit to post in that regard.

I'll get a couple more substantial tasks posted tomorrow too.  I think
in general i need to just start clicking through and looking for
things not working.  I know there will some routes that are post in
routes.rb but get in the app- so we can flip flop either app or routes
where appropriate.

Thanks for the hackin',

M

On Sat, Dec 10, 2011 at 10:26 PM, caryfitzhugh
reply@reply.github.com
wrote:

> Actually, might just need to make the two routes more different - so they
> don't try to recognize each other....  we'll see...
>
