### ISSUE TITLE
Recreate in-place auto_complete_for

### ISSUE THREAD

**Issue by mjy** [mx3/mx#33]
See the images controller for examples `auto_complete_for :image, :maker`.  Rather than storing an id in a hidden field this just queries the existing values present in the database and presents the text as possible options.  You need not select from a list.

To view images->new.  You'll throw a related error.  Code is in images/_form.

**Comment by caryfitzhugh** [comment]
Ok - got started on this - I think I figured it out.  

Adding in some functional tests - which means I need to create some Images on the system.

I added machinst - the factory system we use on Ziplist - which is really handy for creating an object on the fly to test with.

https://github.com/notahat/machinist

I've got it creating my Image, but it doesn't _yet_ set the file right, so I can't create the image (and therefore can't test my copyright_holder and maker autocompletes!)

But hope it will be done shortly.

Thanks,
Cary

**Comment by mjy** [comment]
Check Material -> Collecting Events (Ces) -> New as well. Need that
functionality there, and doesn't come with the Image baggage.

On Tue, Dec 13, 2011 at 10:40 PM, caryfitzhugh
reply@reply.github.com
wrote:

**Comment by caryfitzhugh** [comment]
Got the blueprints working for images, and the two tests running so the images should be working.

I'm going to work next on the CES controller code.  

Thanks!

**Comment by caryfitzhugh** [comment]
Done. Pushed.  :)  Tests and all !

**Comment by mjy** [comment]
Awesome, thanks.
Try to get some more stuff up tomorrow.
M

On Sat, Dec 17, 2011 at 10:23 PM, Cary FitzHugh
reply@reply.github.com
wrote:
