### ISSUE TITLE
Update relationship creation popup to unobtrusive JS

### ISSUE THREAD

**Issue by mjy** [mx3/mx#39]
As with the other popups. Right now they only need to be b/w two ontology_classes, but they are modeled for relationships b/w/ any mx model with a primary key "id".

Create a relationship through the ontology table -> relationships.

Create a couple ontology classes (just provide a bogus definition).

Show one of them.  Click no the "Add relationship" link to the left.

**Comment by caryfitzhugh** [comment]
Looking into this one.

**Comment by caryfitzhugh** [comment]
Done! 
Fixed sensu create / delete buttons, and the relationship create / delete buttons.
