### ISSUE TITLE
Implement generic column sorting for tables

### ISSUE THREAD

**Issue by mjy** [mx3/mx#46]
Assume tables have a header section. Create some generic jQuery code that makes columns sortable for any given table.  I'd prefer to use native mx code.  Don't sweat the CSS (and, as always, no images for buttons/styling).

**Comment by caryfitzhugh** [comment]
Is all the data in the view and I'm just twiddling TR elements?

On Mon, Feb 13, 2012 at 10:16 AM, Matt <
reply@reply.github.com

**Comment by mjy** [comment]
Yes, for now make that assumption.  If people want dynamic views we'll
create a new issue.

On Mon, Feb 13, 2012 at 10:21 AM, Cary FitzHugh
reply@reply.github.com
wrote:

**Comment by caryfitzhugh** [comment]
will work on this next.

**Comment by caryfitzhugh** [comment]
yay. done.
It's pretty simple. I put comments at the top of the js file (jquery.mx-sortable-table.js).

There is an example i was working off of.

I think you would just need to add the data-sortable-table tag to a table.

Add the styles into the SASS stylesheet that you want (i ahve some examples in the example) - like sorted column style.

And then you are good to go. It just twizzles things in place on the page. :)
