### ISSUE TITLE
JS to warn user form is not saved.

### ISSUE THREAD

**Issue by mjy** [mx3/mx#47]
We need a "data-save-warning" (or some such) for input elements.  Input elements, when changed, should fire some JS that  changes the background-color of the bounding form (or perhaps a bounding div).

We could also perhaps inject an element with some text warning  "not saved"  when a user updates an input element, but let's just start with changing the background-color of the form for now.

**Comment by caryfitzhugh** [comment]
Would you also want one of those 'before you leave the page are you sure?' dialogs?

**Comment by mjy** [comment]
Ah- sure, I haven't seen those, but yes, might be very useful
addition.  Feel free to add as another task if it's significantly
different.

M

On Wed, Feb 22, 2012 at 10:31 AM, Cary FitzHugh
reply@reply.github.com
wrote:

**Comment by caryfitzhugh** [comment]
Done and pushed. :)

Example HTML code is at the top of the plugin file in comments.
