### ISSUE TITLE
JS to find related records on new record forms

### ISSUE THREAD

**Issue by mjy** [mx3/mx#48]
We need a generic bit of code, similar to the ajax autocomplete/autofill fields that populates some div based on changes to the input box.  

The example is user clicks to create a new OTU.  User starts to fill in the "name" field for the OTU.  As user types we get an AJAX request that populates a div with a list of OTUs that share that string.  This is very similar to the autocomplete (in fact we might extend the autocomplete code) but it presents the list of results within some associated div.  

data-find-similar-on-change=true
data-find-similar-on-change-target=some_div_id
data-find-similar-on-change-search-type=some_name_to_be_used_in_a_case_statement (i.e. selects the type of search result to look for)

Alternately- another solution would be to be slightly less real-time.  1) On change of an element a button appears beside element that says: "find similar".  When clicked it submits the existing field to a search request of a certain type, and populates the related div. 

Clear as mud?

**Comment by caryfitzhugh** [comment]
So instead of autocompleting - it basically does the same exact thing:

1) watches for changes on the input field.
2) submits a query to the server with term=<value in the input field>
3) puts a spinner on the input field.
4) takes the response, and instead of putting it in a dropdown below the input field - it takes the response and populates a given element on the page

I think an extension to mx-autocomplete may do the trick....

**Comment by caryfitzhugh** [comment]
extension will be more pain than it's worth. Going to write something different to do this.

**Comment by mjy** [comment]
I couldn't find the js that is used for the non-id based autocomplete,
might be easier with that one?

On 2/24/12, Cary FitzHugh
reply@reply.github.com
wrote:

**Comment by caryfitzhugh** [comment]
I just did it and pushed.

Put into data-autoquery="The URL you want to hit (can include query parameters)"
data-autoquery-target="CSS Selector to put the response in"

the autoquery will add a 'term' query parameter which is the value of the input field.

slows down to one request max every 250 ms.

I *think \* that is what you need... yes?  Server side should just return the HTML you want to populate with. :)
