### ISSUE TITLE
Update session references to not store cached instances of AR objects

### ISSUE THREAD

**Issue by mjy** [mx3/mx#57]
Error from http://127.0.0.1:3000/projects/32/ces/new

I think this is related:

See http://stackoverflow.com/questions/6391855/rails-cache-error-in-rails-3-1-typeerror-cant-dump-hash-with-default-proc

We store a cached version of a Proj in the session, and other things- we'll likely have to Marshal these or store Ids and load on each call.

**Comment by caryfitzhugh** [comment]
We store IDs at Ziplist and it works well...

On Wed, Apr 25, 2012 at 5:17 PM, Matt <
reply@reply.github.com

**Comment by mjy** [comment]
Resolved, at least with respect to storing Proj in session.  Will be interesting to see if there is a performance hit (extra query every request).  May have to seriously refactor the multikey ultimately for similar reasons.
