### ISSUE TITLE
Update controller code to fix autocompletes (was Taxon Autocomplete)

### ISSUE THREAD

**Issue by caryfitzhugh** [mx3/mx#6]
When creating a new OTU, noticed that the autocomplete for Taxon Name is not working.

**Comment by mjy** [comment]
We have to update all the controllers to make the new pickers work, this is trivial grind work that we'll take care of- will be assigned to myself and/or Katja.

**Comment by mjy** [comment]
I created a new label "grind" to indicate issues that are more or less thoughtless updates- in most cases we won't be assigning these to you.

**Comment by caryfitzhugh** [comment]
Tag / New has some autocomplete fields which are broke too I think.

**Comment by mjy** [comment]
Right- we haven't got to fixing them yet.  Will prioritize.

On Fri, Sep 9, 2011 at 1:00 AM, caryfitzhugh
reply@reply.github.com
wrote:

**Comment by mjy** [comment]
I've gone through and updated them all, most just use display_name, but that's OK for now.  There is significant merge action that needs to happen with edge down the road.
