### ISSUE TITLE
simple notice styling

### ISSUE THREAD

**Issue by mjy** [mx3/mx#60]
Would like to be able to style our notices according to some arbitrary class like

```
  notice "Foo is a normal status"
  warning notice "Something bad happened, I'm colored differently."
```

How the method is called doesn't really matter, it could be a parameter (`notice "foo", :warning`), but it should be remain as clean as the `notice "foo"` style

I suspect there might be a Railsy way of doing this already?

**Comment by caryfitzhugh** [comment]
If you do:

Notice, warning, error they all should work the same.

Notice "foo"
Warning "foo"
Error "foo"

It may be warn (or warning) don't remember.

And they may not be styled differently yet, but I thought they were....  I
can check.

Cary
On May 12, 2012 12:54 PM, "Matt" <
reply@reply.github.com>
wrote:

**Comment by mjy** [comment]
Well that's a hell of a thing.  Easiest fix you've ever made.
