### ISSUE TITLE
cell ajax binding when rendered from ajax call

### ISSUE THREAD

**Issue by mjy** [mx3/mx#62]
Cary- this is highest priority right now.  

Happening off the cells in routes like /mxes/browse/123

Steps to reproduce.  Create a matrix, characters, otus (i think you know how to do this).  Click browse.  Click one of the cells.  Update the checkboxes.  Submit.  When you click on the same cell it sends a HTML request, not a JS request.  Essentially the 'data-ajax' = 'modal' tag on the link isn't getting bound because the event isn't fired again.  

See views/mxes/cells/cell_none for comments/location of the problem.

**Comment by caryfitzhugh** [comment]
ok - will look!
