### ISSUE TITLE
Matrix show - long load time for chars and otus

### ISSUE THREAD

**Issue by sandrajhall** [mx3/mx#70]
http://mx-dev.nescent.org:3003/projects/1/mxes/1/show_otus
http://mx-dev.nescent.org:3003/projects/1/mxes/1/show_characters

matrix show - side-nav - characters and otu links take incredibly long time (140 seconds) to load on large matrix

**Comment by mjy** [comment]
Sped this up several orders of magnitude, re-open if not fast enough and we'll reconfigure to not show the %coded for large matrices.
