### ISSUE TITLE
Add 'drag to sort' functionality where needed

### ISSUE THREAD

**Issue by sandrajhall** [mx3/mx#71]
Not working on these pages (could be others I haven't seen yet):

http://mx-dev.nescent.org:3003/projects/1/mxes/1/show_sort_characters
http://mx-dev.nescent.org:3003/projects/1/mxes/3/show_sort_otus
http://mx-dev.nescent.org:3003/projects/1/chr_groups/1
http://mx-dev.nescent.org:3003/projects/1/otu_groups/3

**Comment by mjy** [comment]
ChrGroups and OtuGroups work for me, the drag/drop is a little tricky, but once you get used to it it's not a problem.  Fixed the other two.

**Comment by mjy** [comment]
Chr groups is now fixed.
