### ISSUE TITLE
Chr show - Fix "code with this character"

### ISSUE THREAD

**Issue by sandrajhall** [mx3/mx#82]
http://mx-dev.nescent.org:3003/projects/1/chrs/1?target=show

chr show - box-right  "Code with this character" - after selecting the matrix, the only OTU shown is "foo"

**Comment by mjy** [comment]
Fixed in pending commit except that the spinner is not displaying, assigning that to Cary because I'm throwing a blank..  Added logic to not function when number of OTUs is > 300.
