### ISSUE TITLE
data-ajaxify submit as as POST option

### ISSUE THREAD

**Issue by mjy** [mx3/mx#97]
For example, in OTU/chr groups you're removing a character, i.e. altering the database, the request should be a POST not a get. 

<a data-ajaxify='submit' href="<%= url_for(:action=>:remove_chr, :id => @chr_group.id, :chr_id => chrgc.chr.id, :controller => :chr_groups) %>">x</a>

**Comment by caryfitzhugh** [comment]
should be easy to fix.  My new machine should be here shortly! (I hope!)
